.PHONY: clean

CXX_STD = -std=c++17
WARNINGS = -Wall -Wextra -Werror -Wpedantic -pedantic-errors
OPTIMIZE =
DEBUG =
LIB_DIR = lib
LIBRARIES = -lsfml-graphics -lsfml-window -lsfml-system -lm
LIB_INCLUDES = -I${LIB_DIR}/tileson/include

EXEC_NAME = adventure
EXEC_DIR = bin
EXEC = ${EXEC_DIR}/${EXEC_NAME}
OBJ_DIR = obj
SRC_DIR = src
INC_DIR = src
RES_DIR = assets

MAIN_OBJ = ${OBJ_DIR}/main.o
MAIN_SRC = ${SRC_DIR}/main.cxx
DEBUG_HXX = ${INC_DIR}/Debug.hxx
DEBUG_OBJ = ${OBJ_DIR}/Debug.o
DEBUG_SRC = ${SRC_DIR}/Debug.cxx
GAME_ENGINE_HXX = ${INC_DIR}/GameEngine.hxx
GAME_ENGINE_OBJ = ${OBJ_DIR}/GameEngine.o
GAME_ENGINE_SRC = ${SRC_DIR}/GameEngine.cxx
ACTION_HANDLER_HXX = ${INC_DIR}/ActionHandler.hxx
ACTION_HANDLER_OBJ = ${OBJ_DIR}/ActionHandler.o
ACTION_HANDLER_SRC = ${SRC_DIR}/ActionHandler.cxx
INPUT_HANDLER_HXX = ${INC_DIR}/InputHandler.hxx
INPUT_HANDLER_OBJ = ${OBJ_DIR}/InputHandler.o
INPUT_HANDLER_SRC = ${SRC_DIR}/InputHandler.cxx
RENDERER_HXX = ${INC_DIR}/Renderer.hxx
RENDERER_OBJ = ${OBJ_DIR}/Renderer.o
RENDERER_SRC = ${SRC_DIR}/Renderer.cxx
SPRITE_LOADER_HXX = ${INC_DIR}/SpriteLoader.hxx
SPRITE_LOADER_OBJ = ${OBJ_DIR}/SpriteLoader.o
SPRITE_LOADER_SRC = ${SRC_DIR}/SpriteLoader.cxx

all: debug

release: DEBUG = -DNDEBUG
release: OPTIMIZE = -O3
release: ${EXEC_DIR} ${OBJ_DIR} ${EXEC}

debug: DEBUG = -DDEBUG -g
debug: OPTIMIZE = -Og
debug: ${EXEC_DIR} ${OBJ_DIR} ${EXEC}

${EXEC}: ${MAIN_OBJ} ${ACTION_HANDLER_OBJ} ${DEBUG_OBJ} ${GAME_ENGINE_OBJ} ${INPUT_HANDLER_OBJ} ${RENDERER_OBJ} ${SPRITE_LOADER_OBJ}
	${CXX} -o $@ $^ ${LIBRARIES}
	cp -r -f ${RES_DIR} ${EXEC_DIR}/

${MAIN_OBJ}: ${MAIN_SRC} ${DEBUG_HXX} ${GAME_ENGINE_HXX} ${INPUT_HANDLER_HXX} ${RENDERER_HXX} ${SPRITE_LOADER_HXX}
	${CXX} -c -o $@ $< ${LIB_INCLUDES} ${CXX_STD} ${WARNINGS} ${OPTIMIZE} ${DEBUG}

${DEBUG_OBJ}: ${DEBUG_SRC} ${DEBUG_HXX}
	${CXX} -c -o $@ $< ${LIB_INCLUDES} ${CXX_STD} ${WARNINGS} ${OPTIMIZE} ${DEBUG}

${GAME_ENGINE_OBJ}: ${GAME_ENGINE_SRC} ${GAME_ENGINE_HXX} ${ACTION_HANDLER_HXX} ${DEBUG_HXX} ${INPUT_HANDLER_HXX} ${RENDERER_HXX}
	${CXX} -c -o $@ $< ${LIB_INCLUDES} ${CXX_STD} ${WARNINGS} ${OPTIMIZE} ${DEBUG}

${ACTION_HANDLER_OBJ}: ${ACTION_HANDLER_SRC} ${ACTION_HANDLER_HXX} ${DEBUG_HXX} ${INPUT_HANDLER_HXX}
	${CXX} -c -o $@ $< ${LIB_INCLUDES} ${CXX_STD} ${WARNINGS} ${OPTIMIZE} ${DEBUG}

${INPUT_HANDLER_OBJ}: ${INPUT_HANDLER_SRC} ${INPUT_HANDLER_HXX} ${DEBUG_HXX}
	${CXX} -c -o $@ $< ${LIB_INCLUDES} ${CXX_STD} ${WARNINGS} ${OPTIMIZE} ${DEBUG}

${RENDERER_OBJ}: ${RENDERER_SRC} ${RENDERER_HXX} ${DEBUG_HXX} ${SPRITE_LOADER_HXX}
	${CXX} -c -o $@ $< ${LIB_INCLUDES} ${CXX_STD} ${WARNINGS} ${OPTIMIZE} ${DEBUG}

${SPRITE_LOADER_OBJ}: ${SPRITE_LOADER_SRC} ${SPRITE_LOADER_HXX} ${DEBUG_HXX}
	${CXX} -c -o $@ $< ${LIB_INCLUDES} ${CXX_STD} ${WARNINGS} ${OPTIMIZE} ${DEBUG}

${EXEC_DIR}:
	mkdir -p ${EXEC_DIR}

${OBJ_DIR}:
	mkdir -p ${OBJ_DIR}

clean:
	rm -r -f bin obj
